apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: QUEUE_CLUSTER_NAME
  namespace: QUEUE_NAMESPACE
spec:
  replicas: 1
  tls:
    secretName: QUEUE_SECRET # general queue tls key pair
    caSecretName: service-ca-cert # use service ca to authenticate clients
    disableNonTLSListeners: true
  rabbitmq:
    additionalConfig: |
      ssl_options.fail_if_no_peer_cert = true
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 1Gi
