apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-connector-configmap
data:
  OPEN_FAAS_GW_URL: "http://gateway.openfaas.svc.cluster.local:8080"
  RMQ_TOPICS: QUEUE_TOPICS
  RMQ_HOST: "QUEUE_CLUSTER_NAME.QUEUE_NAMESPACE.svc.cluster.local"
  RMQ_PORT: "5671"
  RMQ_USER: QUEUE_USER
  RMQ_PASS: QUEUE_PASS  
  REQ_TIMEOUT: "30s"
  TOPIC_MAP_REFRESH_TIME: "30s"
