apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: db
  namespace: DB_NAMESPACE
spec:
  # Secret names are always required.
  secretName: DB_SECRET
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - kclhi
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
  commonName: "*.DB_NAME-svc.DB_NAMESPACE.svc.cluster.local"
  dnsNames:
    - DB_NAME-0.DB_NAME-svc.DB_NAMESPACE.svc.cluster.local
  # Issuer references are always required.
  issuerRef:
    name: service-ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
