apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: DB_NAME
spec:
  members: 1
  type: ReplicaSet
  version: "4.2.7"
  arbiters: 0
  security:
    authentication:
      modes: ["SCRAM"]
    tls:
      enabled: true
      certificateKeySecretRef:
        name: DB_SECRET
      caConfigMapRef:
        name: db-cert
  users:
    - name: USERNAME
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: MONGO_PASSWORD_SECRET
      roles:
        - name: readWrite
          db: DB_NAME
      scramCredentialsSecretName: SCRAM_SECRET
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
